### ISSUE TITLE
Only one parameters

### ISSUE THREAD

**Issue by Cactucs** [aio1108/taffyGroup#2]
Can you make it possible to use it with just one param?

**Comment by aio1108** [comment]
Hi,
Actually, the length of parameters that this plugin function can accept is variable. 
It depends on the number of columns that you want to group (you can just pass one column name if you only have one column to be grouped).
So, I think this plugin function had met your requirement.
Or, can you describe your issue in more detail?

**Comment by Cactucs** [comment]
Accualy not, beacuse the db().distinct() doen't return array of arrays of strings but array of strings.

**Comment by Cactucs** [comment]
This is the code I added in my code:
    if(!(groups[0] instanceof Array)) {
        groups = [groups];
    }

**Comment by aio1108** [comment]
Hi,
Sorry, my bad.
I understand your issue now, and I think you are right, that's a bug actually.
I borrowed your code and made a little modification for fixing this bug (hope you don't mind), then merge them into the source code.
Really thanks for your response! :)
